ALTER TABLE "store_settings"
  ADD COLUMN IF NOT EXISTS "opening_hours" VARCHAR(500) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "pickup_information" VARCHAR(1000) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "delivery_information" VARCHAR(1000) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "map_embed_url" VARCHAR(2000) NOT NULL DEFAULT '';