import { PaymentProvider, Prisma } from '@prisma/client'
import { env } from '../../config/env.js'
import { HttpError } from '../../utils/http.js'
import { initializePaystackTransaction, verifyPaystackTransaction } from './paystack.provider.js'

// Provider-agnostic abstraction for online payment gateways.
//
// The rest of the application (orders, checkout, admin, notifications) depends
// only on this abstraction and the adapters registered here, so it is never
// coupled to a specific provider's SDK. Paystack-specific logic lives entirely
// in paystack.provider.ts.
//
// The existing bank-transfer flow (OrderPayment + PaymentSubmission) is
// independent of this abstraction and is preserved unchanged.

export type { PaymentProvider } from '@prisma/client'

/** Fields an online payment initialization must provide to the provider. */
export interface PaymentInitInput {
  /** Unique provider reference generated by the application. */
  providerReference: string
  orderNumber: string
  /** Server-computed order total in naira (major unit), as a string. */
  amountInNaira: string
  currency: string
  email: string
  callbackUrl?: string
}

/** Normalized result returned after initializing a payment with a provider. */
export interface PaymentInitResult {
  provider: PaymentProvider
  providerReference: string
  /** Gateway checkout URL the customer is redirected to. */
  authorizationUrl: string
  providerMetadata: Record<string, unknown>
}

/**
 * Provider-level outcome of asking a gateway to verify a transaction.
 * `status` reflects the gateway's own view of the transaction.
 */
export interface PaymentVerifyResult {
  provider: PaymentProvider
  providerReference: string
  status: 'SUCCESSFUL' | 'FAILED' | 'UNCONFIRMED'
  /** Gross amount actually charged to the customer by the provider, in major units, as a string. */
  amountInNaira: string | null
  /** The exact amount this instance asked the provider to collect, in major units, as a string. */
  requestedAmountInNaira: string | null
  /** Provider's own processing charge, in major units, as a string (null when unknown). */
  feesInNaira: string | null
  currency: string | null
  paidAt: string | null
  /** Provider-specific notes, omitted from client-visible responses. */
  providerMetadata?: Record<string, unknown>
}

/** Operations a payment provider adapter must implement. */
export interface PaymentProviderAdapter {
  initialize(input: PaymentInitInput): Promise<PaymentInitResult>
  verify(input: { providerReference: string }): Promise<PaymentVerifyResult>
}

interface PaymentProviderDescriptor {
  provider: PaymentProvider
  label: string
  isConfigured: boolean
}

// The active provider is chosen via PAYMENT_PROVIDER in the environment.
// Unknown or empty values keep online payment disabled.
const ACTIVE_PROVIDER: PaymentProvider | null =
  env.payments.provider === 'PAYSTACK' ? PaymentProvider.PAYSTACK : null

export const getActivePaymentProvider = (): PaymentProvider | null => ACTIVE_PROVIDER

export const getAvailablePaymentProviders = (): PaymentProviderDescriptor[] => {
  const descriptors: PaymentProviderDescriptor[] = [
    {
      provider: PaymentProvider.PAYSTACK,
      label: 'Paystack',
      isConfigured: Boolean(
        env.payments.paystack.secretKey && env.payments.paystack.publicKey,
      ),
    },
  ]
  return descriptors
}

export const isOnlinePaymentEnabled = (): boolean =>
  ACTIVE_PROVIDER !== null && getAvailablePaymentProviders().some(
    (entry) => entry.provider === ACTIVE_PROVIDER && entry.isConfigured,
  )

/**
 * Resolve the adapter for a provider. Throws a customer-friendly error if the
 * provider is not integrated yet, keeping the seam explicit.
 */
export const getProviderAdapter = (provider: PaymentProvider): PaymentProviderAdapter => {
  switch (provider) {
    case PaymentProvider.PAYSTACK:
      return {
        initialize: initializePaystackTransaction,
        verify: async (input) => {
          const result = await verifyPaystackTransaction(input.providerReference)
          return {
            provider: PaymentProvider.PAYSTACK,
            providerReference: result.providerReference,
            status:
              result.status === 'success' ? 'SUCCESSFUL'
                : result.status === 'failed' ? 'FAILED'
                : 'UNCONFIRMED',
            amountInNaira:
              result.amountInKobo === '' ? null
                : new Prisma.Decimal(result.amountInKobo).div(100).toString(),
            requestedAmountInNaira:
              result.requestedAmountInKobo === '' ? null
                : new Prisma.Decimal(result.requestedAmountInKobo).div(100).toString(),
            feesInNaira:
              result.feesInKobo === '' ? null
                : new Prisma.Decimal(result.feesInKobo).div(100).toString(),
            currency: result.currency === '' ? null : result.currency,
            paidAt: result.paidAt,
            providerMetadata: { channel: result.channel },
          }
        },
      }
    default:
      throw new Error(`Payment provider ${provider} is not integrated yet.`)
  }
}

/**
 * Ensure online payment is enabled and fully configured before any gateway
 * operation runs. Returns the active provider once verified.
 */
export const requireOnlinePaymentEnabled = (): PaymentProvider => {
  const provider = ACTIVE_PROVIDER
  if (!provider) {
    throw new HttpError(503, 'Online payment is not enabled for this store.')
  }
  const configured = getAvailablePaymentProviders().find((entry) => entry.provider === provider)?.isConfigured
  if (!configured) {
    throw new HttpError(503, 'Online payment is not configured yet.')
  }
  return provider
}